### ISSUE TITLE
human redable flag for bytes

### ISSUE THREAD

**Issue by graphixillusion** [tamada/wildcat#19]
Hi there. As the title says, what about to add an additional flag (-h maybe?) for an human readable output in the total byte size section? It's a lot more confortable reading file sizes using KB,MB,GB,TB etc...

**Comment by tamada** [comment]
no problem!
I will implement your request in the next version.

thank you for your request!

**Comment by tamada** [comment]
I just implemented your request in version 1.0.3, please find the new version product.

**Comment by graphixillusion** [comment]
@tamada thank you for the ultrafast implementation. Seems to work good!
