### ISSUE TITLE
Hangs when folder is more than 3MB in size

### ISSUE THREAD

**Issue by graphixillusion** [tamada/wildcat#30]
Hi there. As the title says, if you try to run a command to list bytes inside a dir, the app hangs without results if the target dir is bigger than 3MB in size. Previous version 1.0.3 doesn't seem to be affected. Another thing i've noticed is that if the files in the target dir are big in size (like ISO), the app hang too. This happens in both 1.0.3 and 1.1.0

OS: Windows 10

**Comment by tamada** [comment]
Thank you for reporting the bug! 👍 
In my environment, the bug in your report was reproduced, too.
I will try to fix the bug.

**Comment by tamada** [comment]
The true cause of the issue is that the file size is too big for [osaki-lab/iowrapper](https://gitlab.com/osaki-lab/iowrapper).

`osaki-lab/iowrapper` stores whole read data.
Therefore, too big size of file crashes the `iowraper`.
I use `iowrapper` for parsing file types (reading again after matching magic numbers).

To fix the issues, I will introduce my own ReadSeekCloser, to buffer the first some bytes.
I also implement appropriate error handling, since the previous version hushed up the error from Reader.

**Comment by tamada** [comment]
I just fixed the reported bug.
Try wildcat-1.1.1, https://github.com/tamada/wildcat/releases/tag/v1.1.1!

**Comment by graphixillusion** [comment]
@tamada nothing still doesn't work

**Comment by tamada** [comment]
Oh... 😞 
I will try to fix it again.

**Comment by tamada** [comment]
@graphixillusion Sorry for the late reply.

I used the Windows machine from my office (Windows 10) and confirmed the reported bug by running 1.1.1 on PowerShell.
Note that I ran the following commands on the `wildcat-1.1.1` directory.

```
> .\wildcat.exe -N ..\wildcat-1.1.1_windows_amd64.tar.gz
      lines      words characters      bytes
     28,078    132,547  7,481,204  7,778,122 ..\wildcat-1.1.1_windows_amd64.tar.gz
```

As the above, the bug did not reproduce; however, the executable file's name in the distribution file (`wildcat-1.1.1_windows_amd64.tar.gz`) was invalid.
Rename the executable file from `wildcat` to `wildcat.exe,` or re-download the distributed file (I already fixed the current distribution files).

Could you re-confirm the reported bugs are fixed or not on version 1.1.1, please?
If it remains the bug, please tell me more details, such as command line, target files, PowerShell or WSL, …

**Comment by graphixillusion** [comment]
@tamada don't worry, thank you very much for the support! I've just tried the new 1.1.1 but still nothing, it hangs with folders with big files inside.

**Comment by tamada** [comment]
@graphixillusion 
I reconfirm the issue again; however, I could not reproduce the reported bug.
I wonder if it requires much time.
Then, `wildcat` introduced the progress bar option in version 1.2.0.
Please try v1.2.0 by showing the progress bar and wait about a few minutes.

**Comment by graphixillusion** [comment]
@tamada You are right: with the new progress bar i can see what's going on and wildcat does the job indeed. The problem is that is super slow. I have a folder content like this:

File 1 --> 2,60GB
File 2 --> 3,06GB
File 3 --> 844MB
File 4 --> 563bytes

The command: `wildcat -bHNP .` takes more than 5 mins to completes. I can't imagine how much time it takes when you need a scan of a folder with hundreds of big files. The result should be ready almost instantly, atleast if you just need to have a quick summary of the total size of a folder. Sadly, slow like this, is almost unusable in this particular scenario...

**Comment by tamada** [comment]
@graphixillusion Thank you for reporting.

I just opened new issues #40.
Please post the discussion of the speed of wildcat on the new issue, if you need.
This issue will close soon.

**Comment by tamada** [comment]
@graphixillusion Thank you for reporting.
