### ISSUE TITLE
File or directory not found when using directories with spaces in the name with powershell

### ISSUE THREAD

**Issue by graphixillusion** [tamada/wildcat#34]
As the title says, this occurrs only with powershell (cmd.exe works good).

Let's say we have a dir with this name

`"Testing Wildcat"`

If you run this command in powershell:

`wildcat '.\Testing Wildcat'`

this is what you get:

`.\Testing Wildcat": file or directory not found`

**Comment by tamada** [comment]
@graphixillusion Thank you for reporting the bug.

I do not know why; however, I empirically found the following things.
If the directory name contains the space, the given path through Windows Powershell includes double quotes only at the suffix.
As a result, `os.Stat` in Go lang returns an error of invalid path.

Therefore, we try to fix the bug palliatively by removing the double quote in the path only at the suffix.

**Comment by graphixillusion** [comment]
@tamada i've tried the last 1.2 and this bug seems fixed
